### ISSUE TITLE
Any chance of an upgrade to pylint 1.5?

### ISSUE THREAD

**Issue by ilkka** [klen/pylama_pylint#8]
This would fix a major issue for me, where pylint 1.4.x doesn't work if the env variable SHLVL is bigger than 1 (more nested shells). I am running into this because I'm using the node package manager to run pylama.

**Comment by bubenkoff** [comment]
+1

**Comment by ev-agelos** [comment]
+1

**Comment by diefans** [comment]
+1

**Comment by pchomik** [comment]
+1

**Comment by bubenkoff** [comment]
thanks!

On 29 February 2016 at 15:06, Kirill Klenov <notifications@github.com>
wrote:

> Closed #8 <https://github.com/klen/pylama_pylint/issues/8> via 24a0f43
> <https://github.com/klen/pylama_pylint/commit/24a0f43e7b41f1dee7d8a7db8a9363b086be04df>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/klen/pylama_pylint/issues/8#event-571143112>.
>



-- 
Anatoly Bubenkov

**Comment by pchomik** [comment]
thanks
